name 'kbe_perl'
maintainer 'Kyle Evans'
maintainer_email 'kylebe@gmail.com'
license 'all_rights'
description 'Installs/Configures kbe_perl'
long_description 'Installs/Configures kbe_perl'
version '0.1.0'
